import React from 'react';
import parse from 'html-react-parser';

const MainSlider = () => {
    const htmlString = `<section class=main-slider>
 <div class="rev_slider_wrapper fullwidthbanner-container" id=rev_slider_one_wrapper data-source=gallery style=overflow:visible;height:1170px>
 <div class="rev_slider fullwidthabanner revslider-initialised tp-simpleresponsive rev_redraw_on_blurfocus" id=rev_slider_one data-version=5.4.1 style=margin-top:0px;margin-bottom:0px;height:1170px data-slideactive=rs-2>
 <ul class=tp-revslider-mainul style=visibility:visible;display:block;overflow:hidden;width:100%;height:100%;max-height:none;left:0px>
 <li data-index=rs-1 data-transition=zoomout class=tp-revslider-slidesli style=perspective:6000px;width:100%;height:100%;overflow:hidden;z-index:18;visibility:hidden;opacity:0;background-color:rgba(255,255,255,0)>
 <div class=slotholder style=position:absolute;top:0px;left:0px;z-index:0;width:100%;height:100%;visibility:inherit;opacity:1;transform:matrix(1,0,0,1,0,0)><div class="tp-dottedoverlay on"></div><div class="tp-bgimg defaultimg" data-bgcolor=undefined style="background-repeat:no-repeat;background-image:var(--sf-img-88);background-size:cover;background-position:center center;width:100%;height:100%;opacity:0;visibility:hidden;z-index:20" src="images/main-slider/1.webp"></div></div>
 <div class="tp-parallax-wrap sf-hidden" style=position:absolute;display:block;visibility:hidden;left:161px;top:213px;z-index:1></div>
 <div class="tp-parallax-wrap sf-hidden" style=position:absolute;display:block;visibility:hidden;left:161px;top:158px;z-index:1></div>
 <div class="tp-parallax-wrap sf-hidden" style=position:absolute;display:block;visibility:hidden;left:161px;top:260px;z-index:1></div>
 <div class="tp-parallax-wrap sf-hidden" style=position:absolute;display:block;visibility:hidden;left:161px;top:341px;z-index:1></div>
 <div class="tp-parallax-wrap sf-hidden" style=position:absolute;display:block;visibility:hidden;left:161px;top:525px;z-index:1></div>
 <div class="tp-parallax-wrap sf-hidden" style=position:absolute;display:block;visibility:hidden;left:161px;top:619px;z-index:1></div>
 <div class="tp-parallax-wrap sf-hidden" style=position:absolute;display:block;visibility:hidden;left:856px;top:198px;z-index:1></div>
 </li>
 <li data-index=rs-2 data-transition=zoomout class="tp-revslider-slidesli active-revslide" style=perspective:6000px;width:100%;height:100%;overflow:hidden;z-index:20;visibility:inherit;opacity:1;background-color:rgba(255,255,255,0)>
 <div class=slotholder style=position:absolute;top:0px;left:0px;z-index:0;width:100%;height:100%;visibility:inherit;opacity:1;transform:matrix(1,0,0,1,0,0)><div class="tp-dottedoverlay on"></div><div class="tp-bgimg defaultimg" data-bgcolor=undefined style="background-repeat:no-repeat;background-image:var(--sf-img-88);background-size:cover;background-position:center center;width:100%;height:100%;opacity:1;visibility:inherit;z-index:20" src="images/main-slider/1.webp" data-single-file-lazy-loaded-src="undefined"></div></div>
 <div class=tp-parallax-wrap style=position:absolute;display:block;visibility:visible;left:161px;top:213px;z-index:1><div class=tp-loop-wrap style=position:absolute;display:block><div class=tp-mask-wrap style=position:absolute;display:block;overflow:hidden;transform:translate3d(0px,0px,0px)><div class=tp-caption data-paddingbottom=[15,15,15,15] data-paddingleft=[15,15,15,15] data-paddingright=[0,0,0,0] data-paddingtop=[10,10,10,10] data-responsive_offset=on data-type=text data-height=none data-width="['750','750','750','750']" data-whitespace=normal data-hoffset="['0','0','0','0']" data-voffset="['-145','-145','-145','-145']" data-x="['left','left','left','left']" data-y="['middle','middle','middle','middle']" data-textalign="['top','top','top','top']" data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]' id=layer-285825860 style="visibility:inherit;transition:none;line-height:30px;border-width:0px;margin:0px;padding:10px 0px 15px 15px;letter-spacing:0px;font-weight:400;font-size:16px;white-space:normal;min-height:0px;min-width:750px;max-height:none;max-width:750px;opacity:1;transform:matrix3d(1,0,0,0,0,1,0,0,0,0,1,0,0,-18.4067,0,1);transform-origin:50% 50% 0px">
 <div class="icon icon-plane-5 bounce-x"></div>
 </div></div></div></div>
 <div class=tp-parallax-wrap style=position:absolute;display:block;visibility:visible;left:161px;top:158px;z-index:1><div class=tp-loop-wrap style=position:absolute;display:block><div class=tp-mask-wrap style=position:absolute;display:block;overflow:hidden;transform:translate3d(0px,0px,0px)><div class=tp-caption data-paddingbottom=[15,15,15,15] data-paddingleft=[15,15,15,15] data-paddingright=[0,0,0,0] data-paddingtop=[10,10,10,10] data-responsive_offset=on data-type=text data-height=none data-width="['750','750','750','750']" data-whitespace=normal data-hoffset="['0','0','0','0']" data-voffset="['-370','-370','-240','-320']" data-x="['left','left','left','left']" data-y="['middle','middle','middle','middle']" data-textalign="['top','top','top','top']" data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]' id=layer-77142028 style="visibility:inherit;transition:none;line-height:30px;border-width:0px;margin:0px;padding:10px 0px 15px 15px;letter-spacing:0px;font-weight:400;font-size:16px;white-space:normal;min-height:0px;min-width:750px;max-height:none;max-width:750px;opacity:1;transform:matrix3d(1,0,0,0,0,1,0,0,0,0,1,0,0,-4.65225,0,1);transform-origin:50% 50% 0px">
 <span class=sub-title><span style="display:inline-flex;align-items:center;justify-content:center;width:72px;height:72px;background:#1a2e5a;border-radius:14px;box-shadow:0 4px 20px rgba(26,46,90,0.5)"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="44" height="44" fill="none"><rect x="10" y="12" width="12" height="8" rx="1" fill="#fff" opacity="0.9"/><rect x="24" y="12" width="12" height="8" rx="1" fill="#fff" opacity="0.9"/><rect x="38" y="12" width="12" height="8" rx="1" fill="#fff" opacity="0.9"/><line x1="16" y1="12" x2="16" y2="20" stroke="#1a2e5a" stroke-width="1"/><line x1="30" y1="12" x2="30" y2="20" stroke="#1a2e5a" stroke-width="1"/><line x1="44" y1="12" x2="44" y2="20" stroke="#1a2e5a" stroke-width="1"/><rect x="6" y="20" width="52" height="2" rx="1" fill="#fff"/><rect x="8" y="22" width="48" height="12" rx="2" fill="#2563eb" stroke="#fff" stroke-width="1.5"/><circle cx="18" cy="28" r="2" fill="#fff" opacity="0.9"/><circle cx="32" cy="28" r="2" fill="#fff" opacity="0.9"/><circle cx="46" cy="28" r="2" fill="#fff" opacity="0.9"/><path d="M5 34h54l-5 9H10L5 34z" fill="#2563eb" stroke="#fff" stroke-width="1.5"/><path d="M2 47Q10 43 18 47Q26 51 34 47Q42 43 50 47Q57 50 62 47" stroke="#fff" stroke-width="2" fill="none" stroke-linecap="round"/><path d="M4 53Q12 50 20 53Q28 56 36 53Q44 50 52 53" stroke="#fff" stroke-width="1.5" fill="none" opacity="0.65" stroke-linecap="round"/></svg></span> </span>
 </div></div></div></div>
 <div class=tp-parallax-wrap style=position:absolute;display:block;visibility:visible;left:161px;top:260px;z-index:1><div class=tp-loop-wrap style=position:absolute;display:block><div class=tp-mask-wrap style=position:absolute;display:block;overflow:hidden;transform:translate3d(0px,0px,0px)><div class=tp-caption data-paddingbottom=[15,15,15,15] data-paddingleft=[15,15,15,15] data-paddingright=[0,0,0,0] data-paddingtop=[10,10,10,10] data-responsive_offset=on data-type=text data-height=none data-width="['750','750','750','750']" data-whitespace=normal data-hoffset="['0','0','0','0']" data-voffset="['-295','-275','-130','-180']" data-x="['left','left','left','left']" data-y="['middle','middle','middle','middle']" data-textalign="['top','top','top','top']" data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]' id=layer-709298869 style="visibility:inherit;transition:none;line-height:30px;border-width:0px;margin:0px;padding:10px 0px 15px 15px;letter-spacing:0px;font-weight:400;font-size:16px;white-space:normal;min-height:0px;min-width:750px;max-height:none;max-width:750px;opacity:1;transform:matrix3d(1,0,0,0,0,1,0,0,0,0,1,0,0,-2.50008,0,1);transform-origin:50% 50% 0px">
 <span class=sub-title><span>Supply Chain Professionals</span></span>
 </div></div></div></div>
 <div class=tp-parallax-wrap style=position:absolute;display:block;visibility:visible;left:161px;top:341px;z-index:1><div class=tp-loop-wrap style=position:absolute;display:block><div class=tp-mask-wrap style=position:absolute;display:block;overflow:hidden;transform:translate3d(0px,0px,0px)><div class=tp-caption data-paddingbottom=[0,0,0,0] data-paddingleft=[15,15,15,15] data-paddingright=[15,15,15,15] data-paddingtop=[0,0,0,0] data-responsive_offset=on data-type=text data-height=none data-width="['950','750','750','480']" data-whitespace=normal data-hoffset="['0','0','0','0']" data-voffset="['-170','-170','0','-100']" data-x="['left','left','left','left']" data-y="['middle','middle','middle','middle']" data-textalign="['top','top','top','top']" data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]' id=layer-298775036 style="visibility:inherit;transition:none;line-height:30px;border-width:0px;margin:0px;padding:0px 15px;letter-spacing:0px;font-weight:400;font-size:16px;white-space:normal;min-height:0px;min-width:950px;max-height:none;max-width:950px;opacity:1;transform:matrix3d(1,0,0,0,0,1,0,0,0,0,1,0,0,-6.06815,0,1);transform-origin:50% 50% 0px">
 <h1 style="text-transform:uppercase">Providing End To End Solutions</h1>
 </div></div></div></div>
 <div class=tp-parallax-wrap style=position:absolute;display:block;visibility:visible;left:161px;top:525px;z-index:1><div class=tp-loop-wrap style=position:absolute;display:block><div class=tp-mask-wrap style=position:absolute;display:block;overflow:hidden;transform:translate3d(0px,0px,0px)><div class=tp-caption data-paddingbottom=[0,0,0,0] data-paddingleft=[15,15,15,15] data-paddingright=[0,0,0,0] data-paddingtop=[0,0,0,0] data-responsive_offset=on data-type=text data-height=none data-width="['750','750','750','450']" data-whitespace=normal data-hoffset="['0','0','0','0']" data-voffset="['-30','-30','160','10']" data-x="['left','left','left','left']" data-y="['middle','middle','middle','middle']" data-textalign="['top','top','top','top']" data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]' id=layer-46460938 style="visibility:inherit;transition:none;line-height:30px;border-width:0px;margin:0px;padding:0px 0px 0px 15px;letter-spacing:0px;font-weight:400;font-size:16px;white-space:normal;min-height:0px;min-width:750px;max-height:none;max-width:750px;opacity:1;transform:matrix3d(1,0,0,0,0,1,0,0,0,0,1,0,0,-2.50817,0,1);transform-origin:50% 50% 0px">
 <div class=text></div>
 </div></div></div></div>
 <div class=tp-parallax-wrap style=position:absolute;display:block;visibility:visible;left:161px;top:619px;z-index:1><div class=tp-loop-wrap style=position:absolute;display:block><div class=tp-mask-wrap style=position:absolute;display:block;overflow:hidden;transform:translate3d(0px,0px,0px)><div class=tp-caption data-paddingbottom=[0,0,0,0] data-paddingleft=[15,15,15,15] data-paddingright=[15,15,15,15] data-paddingtop=[0,0,0,0] data-responsive_offset=on data-type=text data-height=none data-width="['700','750','700','450']" data-whitespace=normal data-hoffset="['0','0','0','0']" data-voffset="['65','65','270','170']" data-x="['left','left','left','left']" data-y="['middle','middle','middle','middle']" data-textalign="['top','top','top','top']" data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]' id=layer-355934201 style="visibility:inherit;transition:none;line-height:30px;border-width:0px;margin:0px;padding:0px 15px;letter-spacing:0px;font-weight:400;font-size:16px;white-space:normal;min-height:0px;min-width:700px;max-height:none;max-width:700px;opacity:1;transform:matrix3d(1,0,0,0,0,1,0,0,0,0,1,0,0,-2.54862,0,1);transform-origin:50% 50% 0px">
 <span class=btn-title>Our
 Solutions <i class="icon fa fa-long-arrow-right"></i></span></span>
 </div></div></div></div>
 <div class=tp-parallax-wrap style=position:absolute;display:block;visibility:visible;left:856px;top:198px;z-index:1><div class=tp-loop-wrap style=position:absolute;display:block><div class=tp-mask-wrap style=position:absolute;display:block;overflow:hidden;transform:translate3d(0px,0px,0px)><div class=tp-caption data-paddingbottom=[0,0,0,0] data-paddingleft=[15,15,15,15] data-paddingright=[15,15,15,15] data-paddingtop=[0,0,0,0] data-responsive_offset=on data-type=text data-height=none data-whitespace=normal data-hoffset="['695','695','695','695']" data-voffset="['0','0','0','0']" data-x="['left','left','left','left']" data-y="['middle','middle','middle','middle']" data-textalign="['top','top','top','top']" data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]' id=layer-444156035 style="visibility:inherit;transition:none;line-height:0px;border-width:0px;margin:0px;padding:0px 15px;letter-spacing:0px;font-weight:400;font-size:16px;white-space:normal;min-height:0px;min-width:0px;max-height:none;max-width:none;opacity:1;transform:matrix3d(1,0,0,0,0,1,0,0,0,0,1,0,0,-31.3926,0,1);transform-origin:50% 50% 0px">
 <figure class=image><img src="/images/extracted/asset_0.webp" alt style=width:727px;height:774px></figure>
 </div></div></div></div>
 </li>
 </ul>
 <div class="tp-loader off" style=display:none></div><div class=tp-bannertimer style=visibility:visible;width:11%;transform:translate3d(0px,0px,0px)></div><div class="tp-leftarrow tparrows gyges" style=top:50%;transform:matrix(1,0,0,1,0,-70);left:0px;visibility:hidden;opacity:0></div><div class="tp-rightarrow tparrows gyges" style=top:50%;transform:matrix(1,0,0,1,-40,-70);left:100%;visibility:hidden;opacity:0></div></div>
 </div>
 </section>`;
    return (
        <>
            {parse(htmlString)}
        </>
    );
};

export default MainSlider;

